defaults:
  - config
  - override trainer: slurm

task:
  shared_model: false
  in_batch_eval: false
  optim:
    lr: 1e-4
  warmup_steps: 10000

datamodule:
  train_path: /checkpoint/kushall/data/cc_news/cc_news_ict_chunked_train.jsonl
  val_path: /checkpoint/kushall/data/cc_news/cc_news_ict_chunked_dev.jsonl
  test_path: /checkpoint/kushall/data/cc_news/cc_news_ict_chunked_test.jsonl
  batch_size: 32
  val_batch_size: 2
  test_batch_size: 2
  drop_last: false
  use_title: true
  num_workers: 2

trainer:
  gpus: 8
  num_nodes: 8
  max_steps: 100000
  num_sanity_val_steps: 0
  log_every_n_steps: 1000
  gradient_clip_val: 2.0
  accumulate_grad_batches: 1
  precision: 16
  strategy: ddp_sharded
