defaults:
  - config
  - override trainer: slurm

task:
  shared_model: false
  in_batch_eval: false
  optim:
    lr: 1e-4
  warmup_steps: 10000

datamodule:
  train_path: /checkpoint/kushall/data/wikipedia/wiki_ict_train.jsonl
  val_path: /checkpoint/kushall/data/wikipedia/wiki_ict_dev.jsonl
  test_path: /checkpoint/kushall/data/wikipedia/wiki_ict_dev.jsonl
  batch_size: 32
  num_negative: 0
  num_val_negative: 0
  num_test_negative: 0
  val_batch_size: 1
  test_batch_size: 1
  drop_last: false
  use_title: true
  num_workers: 10

trainer:
  gpus: 8
  num_nodes: 8
  num_sanity_val_steps: 0
  log_every_n_steps: 1000
  gradient_clip_val: 2.0
  accumulate_grad_batches: 1
  precision: 16
  strategy: ddp_sharded
