# @package _group_
_target_: dpr_scale.task.cross_encoder_eval_task.RerankCrossEncoderTask
shared_model: false
in_batch_eval: false
# Temporary till we reformat LightningModule
datamodule: null
warmup_steps: null
pretrained_checkpoint_path: null
