# @package _group_
_target_: dpr_scale.task.dpr_task.DenseRetrieverTask
shared_model: false
in_batch_eval: false
# Temporary till we reformat LightningModule
datamodule: null
warmup_steps: 0 # avoid error in inference
pretrained_checkpoint_path:
