# @package _group_
_target_: dpr_scale.task.citadel_eval_task.RerankMultiVecRetrieverTask
shared_model: false
in_batch_eval: false
# Temporary till we reformat LightningModule
datamodule: null
warmup_steps: null
pretrained_checkpoint_path: null
